### ISSUE TITLE
Version of omegaconf and hydra

### ISSUE THREAD

**Issue by im-Kitsch** [frt03/inference-based-rl#1]
Hi, 

looks Hydra and Omegaconf have changed the APIs and I cannot directly use your package from newest version, could you specify the version?

Best,

**Comment by frt03** [comment]
@im-Kitsch
Thanks for pointing it out! Please use the following versions:
```
hydra-core==1.0.6
omegaconf==2.0.6
```

**Comment by im-Kitsch** [comment]
okay, thanks!
