### ISSUE TITLE
Offline Update

### ISSUE THREAD

**Issue by im-Kitsch** [frt03/inference-based-rl#2]
Hi,

thanks for your code. 

I wonder if you could give an example of offline implementation? Does only AWR has offline implementation(seems so) or also AWAC SAC also has offline implementation?

Thanks in advance?

**Comment by frt03** [comment]
@im-Kitsch In our codebase, all algorithms (AWR, SAC, AWAC, MPO) are implemented for online training. You may take a look at the official repo of AWR and AWAC for offline training.
